.Dd $Mdocdate$
.Dt CONSBRI 1
.Os
.Sh NAME
.Nm consbri
.Nd set LCD brightness from command line
.Sh SYNOPSIS
.Nm
.Ar percentage
.Sh DESCRIPTION
.Nm
takes a brightness setting as a percentage.
.Sh FILES
.Nm
operates on the sysfs filesystem; if your LCD isn't present in sysfs,
this program will not work.
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Set the LCD to half-brightness:
.Dl consbri 50
Turn off the LCD:
.Dl consbri 0
Set the LCD to full brightness:
.Dl consbri 100
.Sh DIAGNOSTICS
If
.Nm
fails, it might be for one of the following reasons:
.Bl -bullet -width .Ds
.It
No percentage specified, or a percentage is given outside the accepted
range (0-100).
.It
.Nm
cannot access the appropriate sysfs directory: for example, the backlight
might not be in the expected place, or there might not be a sysfs backlight
control.
.It
.Nm
failed to allocate memory for one of the internal buffers.
.It
.Nm
doesn't have the appropriate permissions to access the backlight files.
.El
.Sh AUTHORS
.Nm
was written by
.An Kyle Isom Aq Mt kyle@tyrfingr.is .
.Sh CAVEATS
As this relies on the Linux-specific sysfs, this will only work on Linux
systems.
.Sh BUGS
Please report bugs to the author.
