.Dd $Mdocdate$
.Dt PROGNAME section
.Os
.Sh NAME
.Nm progname
.Nd one line about what it does
.Sh SYNOPSIS
.Nm
.Op Fl options
.Ar
.Sh DESCRIPTION
.\" .Sh RETURN VALUES
.\" For sections 2, 3, & 9 only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, & 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, & 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, & 8 only.
.\" .Sh ERRORS
.\" For sections 2, 3, & 9 only.
.\" .Sh SEE ALSO
.Sh STANDARDS
.Nm
conforms to
.St ansiC .
.\" .Sh HISTORY
.Sh AUTHORS
.Sh CAVEATS
.Sh BUGS

